services:
  web:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: hotel_web
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/var/www/html
      - ./web/config:/var/www/config
      - ./web/partials:/var/www/partial
      - ./web/lang:/var/www/lang
    networks:
      - public
      - backend
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      # - ai
      - db
    deploy:
      resources:
        limits:
          memory: 500M
  db:
    image: mysql:8.4.7
    container_name: hotel_db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 1024M
  # ai:
  #   build:
  #     context: .
  #     dockerfile: ./ollama
  #   container_name: "hotel_brain"
  #   ports:
  #     - "11434:11434"
  #   entrypoint: ["/bin/bash", "/entrypoint.sh"]
  #   volumes:
  #     - ollama_data:/root/.ollama
  #     - ./ollama/Modelfile:/root/.ollama/Modelfile
  #     - ./ollama/entrypoint.sh:/entrypoint.sh
  #   networks:
  #     - backend
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 3500M
 
volumes:
  db_data:
  ollama_data:

networks:
  public:
  backend: