services:
  web:
    build: 
      context: .
      dockerfile: ./php/Dockerfile
    container_name: hotel_web
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/var/www/html
      - ./web/config:/var/www/config
      - ./web/partials:/var/www/partials
      - ./web/includes:/var/www/includes
      - ./web/lang:/var/www/lang
      - ./web/assets:/var/www/assets
    networks:
      - public
      - backend
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      # - ai
      - db
    deploy:
      resources:
        limits:
          memory: 500M
  db:
    image: mysql:8.4.7
    container_name: hotel_db
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 1024M
  bank:
    build: ./payment-service
    container_name: hotel_bank
    ports:
      - "3000:3000"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 64M
  cdn:
    build: ./cdn-service
    container_name: hotel_cdn
    ports:
      - "4000:4000" 
    volumes:
      - cdn_data:/root/uploads
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 64M
  ai:
    build:
      context: .
      dockerfile: ./ollama
    container_name: "hotel_brain"
    ports:
      - "11434:11434"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama/Modelfile:/root/.ollama/Modelfile
      - ./ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 3500M
 
volumes:
  db_data:
  ollama_data:
  cdn_data:

networks:
  public:
  backend: